language: node_js
node_js:
  - stable
  - lts/*
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm install
          - npx semantic-release
        on:
          branch: master
